// <auto-generated />
namespace MyTelegram.Messenger.Handlers.Messages;
/// <summary>
/// Possible errors
/// Code Type Description
/// 400 CHANNEL_FORUM_MISSING This supergroup is not a forum.
/// 400 CHANNEL_INVALID The provided channel is invalid.
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.createForumTopic"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✔] [Anonymous ✖]
/// </remarks>
internal sealed class CreateForumTopicHandler(ICommandBus commandBus, IIdGenerator idGenerator)
    : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestCreateForumTopic, MyTelegram.Schema.IUpdates>, IObjectHandler
{
    protected override async Task<MyTelegram.Schema.IUpdates> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Messages.RequestCreateForumTopic obj)
    {
        if (obj.Peer is not TInputPeerChannel inputPeerChannel)
            RpcErrors.RpcErrors400.PeerIdInvalid.ThrowRpcError();

        var channelId = inputPeerChannel!.ChannelId;
        var topicId = await idGenerator.NextIdAsync(IdType.MessageId, channelId);
        var date = CurrentDate;

        var aggregateId = ForumTopicId.Create(channelId, topicId);
        await commandBus.PublishAsync(new CreateTopicCommand(
            aggregateId, channelId, topicId, input.UserId,
            obj.Title, obj.IconColor, obj.IconEmojiId, date));

        return new TUpdates
        {
            Updates = new TVector<IUpdate>(
                new TUpdateNewMessage
                {
                    Message = new TMessageService
                    {
                        Id = topicId,
                        Peer = new TPeerChannel { ChannelId = channelId },
                        Date = date,
                        Action = new TMessageActionTopicCreate { Title = obj.Title }
                    },
                    Pts = 0,
                    PtsCount = 0
                }),
            Users = new TVector<IUser>(),
            Chats = new TVector<IChat>(),
            Date = date,
            Seq = 0
        };
    }
}
