// <auto-generated />
namespace MyTelegram.Messenger.Handlers.Messages;
/// <summary>
/// Possible errors
/// Code Type Description
/// 400 CHANNEL_INVALID The provided channel is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.getForumTopics"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class GetForumTopicsHandler(
    IQueryProcessor queryProcessor,
    ILayeredService<IForumTopicsConverter> forumTopicsService)
    : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestGetForumTopics, MyTelegram.Schema.Messages.IForumTopics>, IObjectHandler
{
    protected override async Task<MyTelegram.Schema.Messages.IForumTopics> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Messages.RequestGetForumTopics obj)
    {
        if (obj.Peer is not TInputPeerChannel inputPeerChannel)
            return new TForumTopics { Chats = [], Messages = [], Topics = [], Users = [] };

        var channelId = inputPeerChannel.ChannelId;
        var topics = await queryProcessor.ProcessAsync(
            new GetForumTopicsQuery(channelId, obj.OffsetDate, obj.OffsetId, obj.OffsetTopic, obj.Q, obj.Limit));

        var converter = forumTopicsService.GetConverter(input.Layer);
        var tlTopics = topics.Select(t => converter.ToForumTopic(t)).ToList();

        return new TForumTopics
        {
            Topics = new TVector<IForumTopic>(tlTopics),
            Messages = new TVector<IMessage>(),
            Chats = new TVector<IChat>(),
            Users = new TVector<IUser>(),
            Count = tlTopics.Count
        };
    }
}
