// <auto-generated />
namespace MyTelegram.Messenger.Handlers.Messages;
/// <summary>
/// Possible errors
/// Code Type Description
/// 400 CHANNEL_INVALID The provided channel is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.updatePinnedForumTopic"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class UpdatePinnedForumTopicHandler(ICommandBus commandBus)
    : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestUpdatePinnedForumTopic, MyTelegram.Schema.IUpdates>, IObjectHandler
{
    protected override async Task<MyTelegram.Schema.IUpdates> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Messages.RequestUpdatePinnedForumTopic obj)
    {
        if (obj.Peer is TInputPeerChannel inputPeerChannel)
        {
            var aggregateId = ForumTopicId.Create(inputPeerChannel.ChannelId, obj.TopicId);
            await commandBus.PublishAsync(new EditTopicCommand(
                aggregateId, inputPeerChannel.ChannelId, obj.TopicId,
                null, null, null, null, obj.Pinned));
        }

        return new TUpdates
        {
            Updates = new TVector<IUpdate>(),
            Users = new TVector<IUser>(),
            Chats = new TVector<IChat>(),
            Date = CurrentDate,
            Seq = 0
        };
    }
}
